module.exports = [{
  total: 66,
  id: '1',
  name: '1',
  descriptionPT: 'Dinheiro',
  online: false,
  descriptionES: 'Efectivo',
}, {
  total: 42,
  id: '68',
  name: '68',
  descriptionPT: 'Visa',
  online: true,
  descriptionES: 'Visa',
}, {
  total: 13,
  id: '100',
  name: '100',
  descriptionPT: 'Mastercard',
  online: true,
  descriptionES: 'Mastercard',
}, {
  total: 26,
  id: '95',
  name: '95',
  descriptionPT: 'OCA',
  online: true,
  descriptionES: 'OCA',
}, {
  total: 1,
  id: '10',
  name: '10',
  descriptionPT: 'Canasta Pass',
  online: false,
  descriptionES: 'Canasta Pass',
}, {
  total: 3,
  id: '18',
  name: '18',
  descriptionPT: 'Visa',
  online: false,
  descriptionES: 'Visa',
}, {
  total: 4,
  id: '19',
  name: '19',
  descriptionPT: 'Mastercard',
  online: false,
  descriptionES: 'Mastercard',
}, {
  total: 2,
  id: '36',
  name: '36',
  descriptionPT: 'American Express',
  online: false,
  descriptionES: 'American Express',
}, {
  total: 1,
  id: '80',
  name: '80',
  descriptionPT: 'Ticket Restaurant',
  online: false,
  descriptionES: 'Ticket Restaurant',
}, {
  total: 3,
  id: '81',
  name: '81',
  descriptionPT: 'Ticket Alimentación',
  online: false,
  descriptionES: 'Ticket Alimentación',
}, {
  total: 2,
  id: '82',
  name: '82',
  descriptionPT: 'Sodexo (POS)',
  online: false,
  descriptionES: 'Sodexo (POS)',
}, {
  total: 2,
  id: '114',
  name: '114',
  descriptionPT: 'Spreedly',
  online: true,
  descriptionES: 'Spreedly',
}, {
  total: 8,
  id: '85',
  name: '85',
  descriptionPT: 'Ticket Alimentação',
  online: true,
  descriptionES: 'Ticket Alimentación',
}, {
  total: 8,
  id: '86',
  name: '86',
  descriptionPT: 'Ticket Restaurante',
  online: true,
  descriptionES: 'Ticket Restaurant',
}, {
  total: 1,
  id: '20',
  name: '20',
  descriptionPT: 'Visa Electron',
  online: false,
  descriptionES: 'Visa Electron',
}, {
  total: 1,
  id: '99',
  name: '99',
  descriptionPT: 'Tarjeta D',
  online: false,
  descriptionES: 'Tarjeta D',
}, {
  total: 1,
  id: '21',
  name: '21',
  descriptionPT: 'Maestro',
  online: false,
  descriptionES: 'Maestro',
}];
